<!DOCTYPE html>
<html lang="hu">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Egyedi Kép</title>
</head>
<body>
    <h1>A neked szánt kép:</h1>
    <img id="userImage" src="" alt="Személyre szabott kép" style="max-width: 100%; height: auto;">
    <script>
        // Képek listája (URL-ekkel)
        const images = [
            'https://example.com/kep1.jpg',
            'https://example.com/kep2.jpg',
            'https://example.com/kep3.jpg'
        ];

        // LocalStorage ellenőrzése
        let selectedImage = localStorage.getItem('assignedImage');

        // Ha még nincs tárolt kép, választ egyet véletlenszerűen
        if (!selectedImage) {
            selectedImage = images[Math.floor(Math.random() * images.length)];
            localStorage.setItem('assignedImage', selectedImage);
        }

        // Megjeleníti a képet
        document.getElementById('userImage').src = selectedImage;
    </script>
</body>
</html>
